// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source=server.go -destination=mocks_test.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"
	time "time"

	execution "github.com/afreidah/vagabond/internal/execution"
	jobs "github.com/afreidah/vagabond/internal/jobs"
	ledger "github.com/afreidah/vagabond/internal/ledger"
	plugin "github.com/afreidah/vagabond/internal/plugin"
	quota "github.com/afreidah/vagabond/internal/quota"
	scheduler "github.com/afreidah/vagabond/internal/scheduler"
	gomock "go.uber.org/mock/gomock"
)

// MockserverRegistry is a mock of serverRegistry interface.
type MockserverRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockserverRegistryMockRecorder
	isgomock struct{}
}

// MockserverRegistryMockRecorder is the mock recorder for MockserverRegistry.
type MockserverRegistryMockRecorder struct {
	mock *MockserverRegistry
}

// NewMockserverRegistry creates a new mock instance.
func NewMockserverRegistry(ctrl *gomock.Controller) *MockserverRegistry {
	mock := &MockserverRegistry{ctrl: ctrl}
	mock.recorder = &MockserverRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockserverRegistry) EXPECT() *MockserverRegistryMockRecorder {
	return m.recorder
}

// HasNamespace mocks base method.
func (m *MockserverRegistry) HasNamespace(namespace string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNamespace", namespace)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasNamespace indicates an expected call of HasNamespace.
func (mr *MockserverRegistryMockRecorder) HasNamespace(namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNamespace", reflect.TypeOf((*MockserverRegistry)(nil).HasNamespace), namespace)
}

// Inputs mocks base method.
func (m *MockserverRegistry) Inputs(namespace string, usage func(string, string) (quota.PoolUsage, quota.PoolUsage)) []scheduler.Input {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inputs", namespace, usage)
	ret0, _ := ret[0].([]scheduler.Input)
	return ret0
}

// Inputs indicates an expected call of Inputs.
func (mr *MockserverRegistryMockRecorder) Inputs(namespace, usage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inputs", reflect.TypeOf((*MockserverRegistry)(nil).Inputs), namespace, usage)
}

// Provider mocks base method.
func (m *MockserverRegistry) Provider(name string) (plugin.Provider, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provider", name)
	ret0, _ := ret[0].(plugin.Provider)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Provider indicates an expected call of Provider.
func (mr *MockserverRegistryMockRecorder) Provider(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provider", reflect.TypeOf((*MockserverRegistry)(nil).Provider), name)
}

// Refresh mocks base method.
func (m *MockserverRegistry) Refresh(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockserverRegistryMockRecorder) Refresh(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockserverRegistry)(nil).Refresh), ctx)
}

// MockserverLedger is a mock of serverLedger interface.
type MockserverLedger struct {
	ctrl     *gomock.Controller
	recorder *MockserverLedgerMockRecorder
	isgomock struct{}
}

// MockserverLedgerMockRecorder is the mock recorder for MockserverLedger.
type MockserverLedgerMockRecorder struct {
	mock *MockserverLedger
}

// NewMockserverLedger creates a new mock instance.
func NewMockserverLedger(ctrl *gomock.Controller) *MockserverLedger {
	mock := &MockserverLedger{ctrl: ctrl}
	mock.recorder = &MockserverLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockserverLedger) EXPECT() *MockserverLedgerMockRecorder {
	return m.recorder
}

// PoolUsage mocks base method.
func (m *MockserverLedger) PoolUsage(namespace, provider string) (quota.PoolUsage, quota.PoolUsage) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PoolUsage", namespace, provider)
	ret0, _ := ret[0].(quota.PoolUsage)
	ret1, _ := ret[1].(quota.PoolUsage)
	return ret0, ret1
}

// PoolUsage indicates an expected call of PoolUsage.
func (mr *MockserverLedgerMockRecorder) PoolUsage(namespace, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PoolUsage", reflect.TypeOf((*MockserverLedger)(nil).PoolUsage), namespace, provider)
}

// Reap mocks base method.
func (m *MockserverLedger) Reap(ctx context.Context, resolve ledger.Resolver) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reap", ctx, resolve)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reap indicates an expected call of Reap.
func (mr *MockserverLedgerMockRecorder) Reap(ctx, resolve any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reap", reflect.TypeOf((*MockserverLedger)(nil).Reap), ctx, resolve)
}

// Refresh mocks base method.
func (m *MockserverLedger) Refresh(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockserverLedgerMockRecorder) Refresh(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockserverLedger)(nil).Refresh), ctx)
}

// Refreshed mocks base method.
func (m *MockserverLedger) Refreshed() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refreshed")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Refreshed indicates an expected call of Refreshed.
func (mr *MockserverLedgerMockRecorder) Refreshed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refreshed", reflect.TypeOf((*MockserverLedger)(nil).Refreshed))
}

// Reserve mocks base method.
func (m *MockserverLedger) Reserve(ctx context.Context, id execution.ID, namespace, provider string, e quota.Execution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, id, namespace, provider, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reserve indicates an expected call of Reserve.
func (mr *MockserverLedgerMockRecorder) Reserve(ctx, id, namespace, provider, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockserverLedger)(nil).Reserve), ctx, id, namespace, provider, e)
}

// Settle mocks base method.
func (m *MockserverLedger) Settle(ctx context.Context, id execution.ID, namespace, provider string, actual quota.Execution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Settle", ctx, id, namespace, provider, actual)
	ret0, _ := ret[0].(error)
	return ret0
}

// Settle indicates an expected call of Settle.
func (mr *MockserverLedgerMockRecorder) Settle(ctx, id, namespace, provider, actual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Settle", reflect.TypeOf((*MockserverLedger)(nil).Settle), ctx, id, namespace, provider, actual)
}

// MockserverExecutions is a mock of serverExecutions interface.
type MockserverExecutions struct {
	ctrl     *gomock.Controller
	recorder *MockserverExecutionsMockRecorder
	isgomock struct{}
}

// MockserverExecutionsMockRecorder is the mock recorder for MockserverExecutions.
type MockserverExecutionsMockRecorder struct {
	mock *MockserverExecutions
}

// NewMockserverExecutions creates a new mock instance.
func NewMockserverExecutions(ctrl *gomock.Controller) *MockserverExecutions {
	mock := &MockserverExecutions{ctrl: ctrl}
	mock.recorder = &MockserverExecutionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockserverExecutions) EXPECT() *MockserverExecutionsMockRecorder {
	return m.recorder
}

// ClaimDispatches mocks base method.
func (m *MockserverExecutions) ClaimDispatches(ctx context.Context, owner string, now, until time.Time, skip []execution.ID) ([]*execution.Dispatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDispatches", ctx, owner, now, until, skip)
	ret0, _ := ret[0].([]*execution.Dispatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDispatches indicates an expected call of ClaimDispatches.
func (mr *MockserverExecutionsMockRecorder) ClaimDispatches(ctx, owner, now, until, skip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDispatches", reflect.TypeOf((*MockserverExecutions)(nil).ClaimDispatches), ctx, owner, now, until, skip)
}

// Create mocks base method.
func (m *MockserverExecutions) Create(ctx context.Context, r *execution.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockserverExecutionsMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockserverExecutions)(nil).Create), ctx, r)
}

// CreateDispatch mocks base method.
func (m *MockserverExecutions) CreateDispatch(ctx context.Context, d *execution.Dispatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDispatch", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDispatch indicates an expected call of CreateDispatch.
func (mr *MockserverExecutionsMockRecorder) CreateDispatch(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDispatch", reflect.TypeOf((*MockserverExecutions)(nil).CreateDispatch), ctx, d)
}

// DispatchExecutions mocks base method.
func (m *MockserverExecutions) DispatchExecutions(ctx context.Context, dispatch execution.ID) ([]*execution.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchExecutions", ctx, dispatch)
	ret0, _ := ret[0].([]*execution.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DispatchExecutions indicates an expected call of DispatchExecutions.
func (mr *MockserverExecutionsMockRecorder) DispatchExecutions(ctx, dispatch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchExecutions", reflect.TypeOf((*MockserverExecutions)(nil).DispatchExecutions), ctx, dispatch)
}

// FinishDispatch mocks base method.
func (m *MockserverExecutions) FinishDispatch(ctx context.Context, d *execution.Dispatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishDispatch", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishDispatch indicates an expected call of FinishDispatch.
func (mr *MockserverExecutionsMockRecorder) FinishDispatch(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishDispatch", reflect.TypeOf((*MockserverExecutions)(nil).FinishDispatch), ctx, d)
}

// Get mocks base method.
func (m *MockserverExecutions) Get(ctx context.Context, id execution.ID) (*execution.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*execution.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockserverExecutionsMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockserverExecutions)(nil).Get), ctx, id)
}

// GetDispatch mocks base method.
func (m *MockserverExecutions) GetDispatch(ctx context.Context, id execution.ID) (*execution.Dispatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDispatch", ctx, id)
	ret0, _ := ret[0].(*execution.Dispatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDispatch indicates an expected call of GetDispatch.
func (mr *MockserverExecutionsMockRecorder) GetDispatch(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDispatch", reflect.TypeOf((*MockserverExecutions)(nil).GetDispatch), ctx, id)
}

// Ping mocks base method.
func (m *MockserverExecutions) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockserverExecutionsMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockserverExecutions)(nil).Ping), ctx)
}

// RenewDispatch mocks base method.
func (m *MockserverExecutions) RenewDispatch(ctx context.Context, id execution.ID, owner string, until time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewDispatch", ctx, id, owner, until)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenewDispatch indicates an expected call of RenewDispatch.
func (mr *MockserverExecutionsMockRecorder) RenewDispatch(ctx, id, owner, until any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewDispatch", reflect.TypeOf((*MockserverExecutions)(nil).RenewDispatch), ctx, id, owner, until)
}

// Update mocks base method.
func (m *MockserverExecutions) Update(ctx context.Context, r *execution.Record, from execution.State) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, r, from)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockserverExecutionsMockRecorder) Update(ctx, r, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockserverExecutions)(nil).Update), ctx, r, from)
}

// MockserverJobs is a mock of serverJobs interface.
type MockserverJobs struct {
	ctrl     *gomock.Controller
	recorder *MockserverJobsMockRecorder
	isgomock struct{}
}

// MockserverJobsMockRecorder is the mock recorder for MockserverJobs.
type MockserverJobsMockRecorder struct {
	mock *MockserverJobs
}

// NewMockserverJobs creates a new mock instance.
func NewMockserverJobs(ctrl *gomock.Controller) *MockserverJobs {
	mock := &MockserverJobs{ctrl: ctrl}
	mock.recorder = &MockserverJobsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockserverJobs) EXPECT() *MockserverJobsMockRecorder {
	return m.recorder
}

// Job mocks base method.
func (m *MockserverJobs) Job(ctx context.Context, namespace, name string) (*jobs.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Job", ctx, namespace, name)
	ret0, _ := ret[0].(*jobs.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Job indicates an expected call of Job.
func (mr *MockserverJobsMockRecorder) Job(ctx, namespace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Job", reflect.TypeOf((*MockserverJobs)(nil).Job), ctx, namespace, name)
}

// JobExecutions mocks base method.
func (m *MockserverJobs) JobExecutions(ctx context.Context, namespace, job string, limit int) ([]*execution.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobExecutions", ctx, namespace, job, limit)
	ret0, _ := ret[0].([]*execution.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JobExecutions indicates an expected call of JobExecutions.
func (mr *MockserverJobsMockRecorder) JobExecutions(ctx, namespace, job, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobExecutions", reflect.TypeOf((*MockserverJobs)(nil).JobExecutions), ctx, namespace, job, limit)
}

// Jobs mocks base method.
func (m *MockserverJobs) Jobs(ctx context.Context, namespace string) ([]*jobs.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Jobs", ctx, namespace)
	ret0, _ := ret[0].([]*jobs.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Jobs indicates an expected call of Jobs.
func (mr *MockserverJobsMockRecorder) Jobs(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Jobs", reflect.TypeOf((*MockserverJobs)(nil).Jobs), ctx, namespace)
}

// Register mocks base method.
func (m *MockserverJobs) Register(ctx context.Context, namespace, name string, source []byte, now time.Time) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, namespace, name, source, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Register indicates an expected call of Register.
func (mr *MockserverJobsMockRecorder) Register(ctx, namespace, name, source, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockserverJobs)(nil).Register), ctx, namespace, name, source, now)
}

// Stop mocks base method.
func (m *MockserverJobs) Stop(ctx context.Context, namespace, name string, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, namespace, name, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockserverJobsMockRecorder) Stop(ctx, namespace, name, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockserverJobs)(nil).Stop), ctx, namespace, name, now)
}

// Version mocks base method.
func (m *MockserverJobs) Version(ctx context.Context, namespace, name string, version int64) (*jobs.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version", ctx, namespace, name, version)
	ret0, _ := ret[0].(*jobs.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Version indicates an expected call of Version.
func (mr *MockserverJobsMockRecorder) Version(ctx, namespace, name, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockserverJobs)(nil).Version), ctx, namespace, name, version)
}

// Versions mocks base method.
func (m *MockserverJobs) Versions(ctx context.Context, namespace, name string) ([]*jobs.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Versions", ctx, namespace, name)
	ret0, _ := ret[0].([]*jobs.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Versions indicates an expected call of Versions.
func (mr *MockserverJobsMockRecorder) Versions(ctx, namespace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Versions", reflect.TypeOf((*MockserverJobs)(nil).Versions), ctx, namespace, name)
}
