// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dispatches.sql

package db

import (
	"context"
	"time"
)

const createDispatch = `-- name: CreateDispatch :exec

INSERT INTO dispatches (dispatch_id, namespace, job, job_version, state, error, created_at, ended_at)
VALUES ($1, $2, $3, $4, $5, '', $6, NULL)
`

type CreateDispatchParams struct {
	DispatchID string
	Namespace  string
	Job        string
	JobVersion int64
	State      string
	CreatedAt  time.Time
}

// -----------------------------------------------------------------------------
// Dispatch records.
//
// Finishing changes only a dispatch still running, so a late or repeated
// finish cannot overwrite how a run ended.
// -----------------------------------------------------------------------------
func (q *Queries) CreateDispatch(ctx context.Context, arg CreateDispatchParams) error {
	_, err := q.db.Exec(ctx, createDispatch,
		arg.DispatchID,
		arg.Namespace,
		arg.Job,
		arg.JobVersion,
		arg.State,
		arg.CreatedAt,
	)
	return err
}

const finishDispatch = `-- name: FinishDispatch :execrows
UPDATE dispatches SET state = $1, error = $2, ended_at = $3
WHERE dispatch_id = $4 AND state = 'running'
`

type FinishDispatchParams struct {
	State      string
	Error      string
	EndedAt    *time.Time
	DispatchID string
}

func (q *Queries) FinishDispatch(ctx context.Context, arg FinishDispatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishDispatch,
		arg.State,
		arg.Error,
		arg.EndedAt,
		arg.DispatchID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDispatch = `-- name: GetDispatch :one
SELECT dispatch_id, namespace, job, job_version, state, error, created_at, ended_at FROM dispatches WHERE dispatch_id = $1
`

func (q *Queries) GetDispatch(ctx context.Context, dispatchID string) (Dispatch, error) {
	row := q.db.QueryRow(ctx, getDispatch, dispatchID)
	var i Dispatch
	err := row.Scan(
		&i.DispatchID,
		&i.Namespace,
		&i.Job,
		&i.JobVersion,
		&i.State,
		&i.Error,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}
