// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dispatches.sql

package db

import (
	"context"
	"time"
)

const claimDispatches = `-- name: ClaimDispatches :many
UPDATE dispatches SET owner = $1, lease_until = $2
WHERE state = 'running' AND lease_until < $3::timestamptz
  AND NOT (dispatch_id = ANY($4::text[]))
RETURNING dispatch_id, namespace, job, job_version, state, error, created_at, ended_at, tasks, owner, lease_until
`

type ClaimDispatchesParams struct {
	Owner      string
	LeaseUntil time.Time
	Now        time.Time
	Skip       []string
}

// Takes over every running dispatch whose lease lapsed before now, except
// those the caller is running itself. One statement, so two servers claiming
// at once never both get the same one.
func (q *Queries) ClaimDispatches(ctx context.Context, arg ClaimDispatchesParams) ([]Dispatch, error) {
	rows, err := q.db.Query(ctx, claimDispatches,
		arg.Owner,
		arg.LeaseUntil,
		arg.Now,
		arg.Skip,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dispatch{}
	for rows.Next() {
		var i Dispatch
		if err := rows.Scan(
			&i.DispatchID,
			&i.Namespace,
			&i.Job,
			&i.JobVersion,
			&i.State,
			&i.Error,
			&i.CreatedAt,
			&i.EndedAt,
			&i.Tasks,
			&i.Owner,
			&i.LeaseUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDispatch = `-- name: CreateDispatch :exec

INSERT INTO dispatches (
    dispatch_id, namespace, job, job_version, state, error, created_at, ended_at,
    tasks, owner, lease_until
) VALUES (
    $1, $2, $3, $4, $5, '', $6, NULL,
    $7, $8, $9
)
`

type CreateDispatchParams struct {
	DispatchID string
	Namespace  string
	Job        string
	JobVersion int64
	State      string
	CreatedAt  time.Time
	Tasks      int64
	Owner      string
	LeaseUntil time.Time
}

// -----------------------------------------------------------------------------
// Dispatch records.
//
// Finishing and renewing change only a dispatch still running and still held
// by the caller, so a late finish, or one from an owner whose lease was taken
// over, cannot overwrite how a run ended.
// -----------------------------------------------------------------------------
func (q *Queries) CreateDispatch(ctx context.Context, arg CreateDispatchParams) error {
	_, err := q.db.Exec(ctx, createDispatch,
		arg.DispatchID,
		arg.Namespace,
		arg.Job,
		arg.JobVersion,
		arg.State,
		arg.CreatedAt,
		arg.Tasks,
		arg.Owner,
		arg.LeaseUntil,
	)
	return err
}

const finishDispatch = `-- name: FinishDispatch :execrows
UPDATE dispatches SET state = $1, error = $2, ended_at = $3
WHERE dispatch_id = $4 AND state = 'running' AND owner = $5
`

type FinishDispatchParams struct {
	State      string
	Error      string
	EndedAt    *time.Time
	DispatchID string
	Owner      string
}

func (q *Queries) FinishDispatch(ctx context.Context, arg FinishDispatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishDispatch,
		arg.State,
		arg.Error,
		arg.EndedAt,
		arg.DispatchID,
		arg.Owner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDispatch = `-- name: GetDispatch :one
SELECT dispatch_id, namespace, job, job_version, state, error, created_at, ended_at, tasks, owner, lease_until FROM dispatches WHERE dispatch_id = $1
`

func (q *Queries) GetDispatch(ctx context.Context, dispatchID string) (Dispatch, error) {
	row := q.db.QueryRow(ctx, getDispatch, dispatchID)
	var i Dispatch
	err := row.Scan(
		&i.DispatchID,
		&i.Namespace,
		&i.Job,
		&i.JobVersion,
		&i.State,
		&i.Error,
		&i.CreatedAt,
		&i.EndedAt,
		&i.Tasks,
		&i.Owner,
		&i.LeaseUntil,
	)
	return i, err
}

const renewDispatch = `-- name: RenewDispatch :execrows
UPDATE dispatches SET lease_until = $1
WHERE dispatch_id = $2 AND state = 'running' AND owner = $3
`

type RenewDispatchParams struct {
	LeaseUntil time.Time
	DispatchID string
	Owner      string
}

func (q *Queries) RenewDispatch(ctx context.Context, arg RenewDispatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewDispatch, arg.LeaseUntil, arg.DispatchID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
