// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executions.sql

package db

import (
	"context"
	"time"
)

const createExecution = `-- name: CreateExecution :exec

INSERT INTO executions (
    id, namespace, job, job_version, task, provider, attempt, previous_id,
    state, provider_id, failure, created_at, started_at, ended_at, updated_at,
    exit_code, duration_ms, billed_cpu, billed_memory, billed_ms, logs, logs_truncated
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21, $22
)
`

type CreateExecutionParams struct {
	ID            string
	Namespace     string
	Job           string
	JobVersion    int64
	Task          string
	Provider      string
	Attempt       int64
	PreviousID    string
	State         string
	ProviderID    string
	Failure       string
	CreatedAt     time.Time
	StartedAt     *time.Time
	EndedAt       *time.Time
	UpdatedAt     time.Time
	ExitCode      *int64
	DurationMs    *int64
	BilledCpu     *int64
	BilledMemory  *int64
	BilledMs      *int64
	Logs          []byte
	LogsTruncated bool
}

// -----------------------------------------------------------------------------
// Execution records.
//
// An update names the state the caller read the record in and changes nothing
// if it has moved since, so two writers cannot silently overwrite each other.
// -----------------------------------------------------------------------------
func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) error {
	_, err := q.db.Exec(ctx, createExecution,
		arg.ID,
		arg.Namespace,
		arg.Job,
		arg.JobVersion,
		arg.Task,
		arg.Provider,
		arg.Attempt,
		arg.PreviousID,
		arg.State,
		arg.ProviderID,
		arg.Failure,
		arg.CreatedAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ExitCode,
		arg.DurationMs,
		arg.BilledCpu,
		arg.BilledMemory,
		arg.BilledMs,
		arg.Logs,
		arg.LogsTruncated,
	)
	return err
}

const getExecution = `-- name: GetExecution :one
SELECT id, namespace, job, job_version, task, provider, attempt, previous_id, state, provider_id, failure, created_at, started_at, ended_at, updated_at, exit_code, duration_ms, billed_cpu, billed_memory, billed_ms, logs, logs_truncated FROM executions WHERE id = $1
`

func (q *Queries) GetExecution(ctx context.Context, id string) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecution, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Job,
		&i.JobVersion,
		&i.Task,
		&i.Provider,
		&i.Attempt,
		&i.PreviousID,
		&i.State,
		&i.ProviderID,
		&i.Failure,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
		&i.ExitCode,
		&i.DurationMs,
		&i.BilledCpu,
		&i.BilledMemory,
		&i.BilledMs,
		&i.Logs,
		&i.LogsTruncated,
	)
	return i, err
}

const updateExecution = `-- name: UpdateExecution :execrows
UPDATE executions SET
    state          = $1,
    provider_id    = $2,
    failure        = $3,
    started_at     = $4,
    ended_at       = $5,
    updated_at     = $6,
    exit_code      = $7,
    duration_ms    = $8,
    billed_cpu     = $9,
    billed_memory  = $10,
    billed_ms      = $11,
    logs           = $12,
    logs_truncated = $13
WHERE id = $14 AND state = $15::text
`

type UpdateExecutionParams struct {
	State         string
	ProviderID    string
	Failure       string
	StartedAt     *time.Time
	EndedAt       *time.Time
	UpdatedAt     time.Time
	ExitCode      *int64
	DurationMs    *int64
	BilledCpu     *int64
	BilledMemory  *int64
	BilledMs      *int64
	Logs          []byte
	LogsTruncated bool
	ID            string
	FromState     string
}

// Writes everything that changes after creation, only if the record is still
// in from_state.
func (q *Queries) UpdateExecution(ctx context.Context, arg UpdateExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExecution,
		arg.State,
		arg.ProviderID,
		arg.Failure,
		arg.StartedAt,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.ExitCode,
		arg.DurationMs,
		arg.BilledCpu,
		arg.BilledMemory,
		arg.BilledMs,
		arg.Logs,
		arg.LogsTruncated,
		arg.ID,
		arg.FromState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
