// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
	"time"
)

const currentJobVersion = `-- name: CurrentJobVersion :one

SELECT j.version, j.stopped, v.fingerprint
FROM jobs j
JOIN job_versions v
  ON v.namespace = j.namespace AND v.name = j.name AND v.version = j.version
WHERE j.namespace = $1 AND j.name = $2
`

type CurrentJobVersionParams struct {
	Namespace string
	Name      string
}

type CurrentJobVersionRow struct {
	Version     int64
	Stopped     bool
	Fingerprint string
}

// -----------------------------------------------------------------------------
// Registered jobs.
//
// Registering is several statements in one serializable transaction: read the
// current version, and only if the job changed, insert the next and point the
// job at it. Two registers racing conflict and one is retried.
// -----------------------------------------------------------------------------
func (q *Queries) CurrentJobVersion(ctx context.Context, arg CurrentJobVersionParams) (CurrentJobVersionRow, error) {
	row := q.db.QueryRow(ctx, currentJobVersion, arg.Namespace, arg.Name)
	var i CurrentJobVersionRow
	err := row.Scan(&i.Version, &i.Stopped, &i.Fingerprint)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT namespace, name, version, stopped, updated_at
FROM jobs
WHERE namespace = $1 AND name = $2
`

type GetJobParams struct {
	Namespace string
	Name      string
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.Namespace, arg.Name)
	var i Job
	err := row.Scan(
		&i.Namespace,
		&i.Name,
		&i.Version,
		&i.Stopped,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobVersion = `-- name: GetJobVersion :one
SELECT namespace, name, version, source, fingerprint, created_at
FROM job_versions
WHERE namespace = $1 AND name = $2 AND version = $3
`

type GetJobVersionParams struct {
	Namespace string
	Name      string
	Version   int64
}

func (q *Queries) GetJobVersion(ctx context.Context, arg GetJobVersionParams) (JobVersion, error) {
	row := q.db.QueryRow(ctx, getJobVersion, arg.Namespace, arg.Name, arg.Version)
	var i JobVersion
	err := row.Scan(
		&i.Namespace,
		&i.Name,
		&i.Version,
		&i.Source,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const insertJobVersion = `-- name: InsertJobVersion :exec
INSERT INTO job_versions (namespace, name, version, source, fingerprint, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertJobVersionParams struct {
	Namespace   string
	Name        string
	Version     int64
	Source      string
	Fingerprint string
	CreatedAt   time.Time
}

func (q *Queries) InsertJobVersion(ctx context.Context, arg InsertJobVersionParams) error {
	_, err := q.db.Exec(ctx, insertJobVersion,
		arg.Namespace,
		arg.Name,
		arg.Version,
		arg.Source,
		arg.Fingerprint,
		arg.CreatedAt,
	)
	return err
}

const listJobVersions = `-- name: ListJobVersions :many
SELECT namespace, name, version, fingerprint, created_at
FROM job_versions
WHERE namespace = $1 AND name = $2
ORDER BY version DESC
`

type ListJobVersionsParams struct {
	Namespace string
	Name      string
}

type ListJobVersionsRow struct {
	Namespace   string
	Name        string
	Version     int64
	Fingerprint string
	CreatedAt   time.Time
}

// Newest first, without the source.
func (q *Queries) ListJobVersions(ctx context.Context, arg ListJobVersionsParams) ([]ListJobVersionsRow, error) {
	rows, err := q.db.Query(ctx, listJobVersions, arg.Namespace, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobVersionsRow{}
	for rows.Next() {
		var i ListJobVersionsRow
		if err := rows.Scan(
			&i.Namespace,
			&i.Name,
			&i.Version,
			&i.Fingerprint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT namespace, name, version, stopped, updated_at
FROM jobs
WHERE namespace = $1
ORDER BY name
`

func (q *Queries) ListJobs(ctx context.Context, namespace string) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Namespace,
			&i.Name,
			&i.Version,
			&i.Stopped,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pointJobAt = `-- name: PointJobAt :exec
INSERT INTO jobs (namespace, name, version, stopped, updated_at)
VALUES ($1, $2, $3, FALSE, $4)
ON CONFLICT (namespace, name) DO UPDATE SET
    version    = EXCLUDED.version,
    stopped    = FALSE,
    updated_at = EXCLUDED.updated_at
`

type PointJobAtParams struct {
	Namespace string
	Name      string
	Version   int64
	UpdatedAt time.Time
}

// Makes version current and the job dispatchable again.
func (q *Queries) PointJobAt(ctx context.Context, arg PointJobAtParams) error {
	_, err := q.db.Exec(ctx, pointJobAt,
		arg.Namespace,
		arg.Name,
		arg.Version,
		arg.UpdatedAt,
	)
	return err
}

const stopJob = `-- name: StopJob :execrows
UPDATE jobs SET stopped = TRUE, updated_at = $1
WHERE namespace = $2 AND name = $3
`

type StopJobParams struct {
	UpdatedAt time.Time
	Namespace string
	Name      string
}

func (q *Queries) StopJob(ctx context.Context, arg StopJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopJob, arg.UpdatedAt, arg.Namespace, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
