// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Execution struct {
	ID            string
	Namespace     string
	Job           string
	JobVersion    int64
	Task          string
	Provider      string
	Attempt       int64
	PreviousID    string
	State         string
	ProviderID    string
	Failure       string
	CreatedAt     time.Time
	StartedAt     *time.Time
	EndedAt       *time.Time
	UpdatedAt     time.Time
	ExitCode      *int64
	DurationMs    *int64
	BilledCpu     *int64
	BilledMemory  *int64
	BilledMs      *int64
	Logs          []byte
	LogsTruncated bool
}

type QuotaReservation struct {
	ExecutionID string
	Provider    string
	Pool        string
	Period      string
	Amount      int64
	Cpu         int64
	Memory      int64
	CreatedAt   time.Time
	Namespace   string
}

type QuotaUsage struct {
	Provider  string
	Pool      string
	Period    string
	Used      int64
	UpdatedAt time.Time
	Namespace string
}
