// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type QuotaReservation struct {
	ExecutionID string
	Provider    string
	Pool        string
	Period      string
	Amount      int64
	Cpu         int64
	Memory      int64
	CreatedAt   time.Time
	Namespace   string
}

type QuotaUsage struct {
	Provider  string
	Pool      string
	Period    string
	Used      int64
	UpdatedAt time.Time
	Namespace string
}
