// -----------------------------------------------------------------------------
// Agent Protocol
//
// Author: Alex Freidah
//
// What a server and its agents say to each other. The agent dials the server
// and both sides run gRPC over streams of that one multiplexed connection:
// Node is served by the server and called by the agent, AgentExecutions is
// served by the agent and called by the server.
// -----------------------------------------------------------------------------

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: internal/agentrpc/agent.proto

package agentrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Node_Register_FullMethodName = "/vagabond.agent.v1.Node/Register"
)

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeClient interface {
	// Register announces the node when the agent connects, and again whenever
	// what it reports changes.
	Register(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error)
}

type nodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeClient(cc grpc.ClientConnInterface) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Register(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRegisterResponse)
	err := c.cc.Invoke(ctx, Node_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility.
type NodeServer interface {
	// Register announces the node when the agent connects, and again whenever
	// what it reports changes.
	Register(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error)
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServer struct{}

func (UnimplementedNodeServer) Register(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}
func (UnimplementedNodeServer) testEmbeddedByValue()              {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	// If the following call panics, it indicates UnimplementedNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Register(ctx, req.(*NodeRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vagabond.agent.v1.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Node_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/agentrpc/agent.proto",
}

const (
	AgentExecutions_Submit_FullMethodName     = "/vagabond.agent.v1.AgentExecutions/Submit"
	AgentExecutions_Status_FullMethodName     = "/vagabond.agent.v1.AgentExecutions/Status"
	AgentExecutions_Result_FullMethodName     = "/vagabond.agent.v1.AgentExecutions/Result"
	AgentExecutions_Cancel_FullMethodName     = "/vagabond.agent.v1.AgentExecutions/Cancel"
	AgentExecutions_Release_FullMethodName    = "/vagabond.agent.v1.AgentExecutions/Release"
	AgentExecutions_StreamLogs_FullMethodName = "/vagabond.agent.v1.AgentExecutions/StreamLogs"
)

// AgentExecutionsClient is the client API for AgentExecutions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentExecutionsClient interface {
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*Submission, error)
	Status(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionStatus, error)
	Result(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResult, error)
	Cancel(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*Empty, error)
	Release(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*Empty, error)
	StreamLogs(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
}

type agentExecutionsClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentExecutionsClient(cc grpc.ClientConnInterface) AgentExecutionsClient {
	return &agentExecutionsClient{cc}
}

func (c *agentExecutionsClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*Submission, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Submission)
	err := c.cc.Invoke(ctx, AgentExecutions_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentExecutionsClient) Status(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionStatus)
	err := c.cc.Invoke(ctx, AgentExecutions_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentExecutionsClient) Result(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResult)
	err := c.cc.Invoke(ctx, AgentExecutions_Result_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentExecutionsClient) Cancel(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AgentExecutions_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentExecutionsClient) Release(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AgentExecutions_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentExecutionsClient) StreamLogs(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentExecutions_ServiceDesc.Streams[0], AgentExecutions_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecutionRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentExecutions_StreamLogsClient = grpc.ServerStreamingClient[LogChunk]

// AgentExecutionsServer is the server API for AgentExecutions service.
// All implementations must embed UnimplementedAgentExecutionsServer
// for forward compatibility.
type AgentExecutionsServer interface {
	Submit(context.Context, *SubmitRequest) (*Submission, error)
	Status(context.Context, *ExecutionRequest) (*ExecutionStatus, error)
	Result(context.Context, *ExecutionRequest) (*ExecutionResult, error)
	Cancel(context.Context, *ExecutionRequest) (*Empty, error)
	Release(context.Context, *ExecutionRequest) (*Empty, error)
	StreamLogs(*ExecutionRequest, grpc.ServerStreamingServer[LogChunk]) error
	mustEmbedUnimplementedAgentExecutionsServer()
}

// UnimplementedAgentExecutionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentExecutionsServer struct{}

func (UnimplementedAgentExecutionsServer) Submit(context.Context, *SubmitRequest) (*Submission, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedAgentExecutionsServer) Status(context.Context, *ExecutionRequest) (*ExecutionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedAgentExecutionsServer) Result(context.Context, *ExecutionRequest) (*ExecutionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedAgentExecutionsServer) Cancel(context.Context, *ExecutionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedAgentExecutionsServer) Release(context.Context, *ExecutionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedAgentExecutionsServer) StreamLogs(*ExecutionRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedAgentExecutionsServer) mustEmbedUnimplementedAgentExecutionsServer() {}
func (UnimplementedAgentExecutionsServer) testEmbeddedByValue()                         {}

// UnsafeAgentExecutionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentExecutionsServer will
// result in compilation errors.
type UnsafeAgentExecutionsServer interface {
	mustEmbedUnimplementedAgentExecutionsServer()
}

func RegisterAgentExecutionsServer(s grpc.ServiceRegistrar, srv AgentExecutionsServer) {
	// If the following call panics, it indicates UnimplementedAgentExecutionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentExecutions_ServiceDesc, srv)
}

func _AgentExecutions_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentExecutionsServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentExecutions_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentExecutionsServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentExecutions_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentExecutionsServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentExecutions_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentExecutionsServer).Status(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentExecutions_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentExecutionsServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentExecutions_Result_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentExecutionsServer).Result(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentExecutions_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentExecutionsServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentExecutions_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentExecutionsServer).Cancel(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentExecutions_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentExecutionsServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentExecutions_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentExecutionsServer).Release(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentExecutions_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecutionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentExecutionsServer).StreamLogs(m, &grpc.GenericServerStream[ExecutionRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentExecutions_StreamLogsServer = grpc.ServerStreamingServer[LogChunk]

// AgentExecutions_ServiceDesc is the grpc.ServiceDesc for AgentExecutions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentExecutions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vagabond.agent.v1.AgentExecutions",
	HandlerType: (*AgentExecutionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _AgentExecutions_Submit_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _AgentExecutions_Status_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _AgentExecutions_Result_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _AgentExecutions_Cancel_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _AgentExecutions_Release_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _AgentExecutions_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/agentrpc/agent.proto",
}
