// -----------------------------------------------------------------------------
// Agent Protocol
//
// Author: Alex Freidah
//
// What a server and its agents say to each other. The agent dials the server
// and both sides run gRPC over streams of that one multiplexed connection:
// Node is served by the server and called by the agent, AgentExecutions is
// served by the agent and called by the server.
// -----------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: internal/agentrpc/agent.proto

package agentrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeRegisterRequest is one agent's node as it reports itself, sent when it
// connects and again whenever its workloads change. capacity is the smallest
// of the host's resources, the agent's cgroup limits, and its flags. held is
// every workload it still holds, so a server knows what is placed where and
// how much of the node is in use, after either side restarts.
type NodeRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pool          string                 `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Architecture  string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Capacity      *Resources             `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Runtimes      []string               `protobuf:"bytes,6,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Held          []*Held                `protobuf:"bytes,8,rep,name=held,proto3" json:"held,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegisterRequest) Reset() {
	*x = NodeRegisterRequest{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegisterRequest) ProtoMessage() {}

func (x *NodeRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegisterRequest.ProtoReflect.Descriptor instead.
func (*NodeRegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{0}
}

func (x *NodeRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeRegisterRequest) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *NodeRegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *NodeRegisterRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *NodeRegisterRequest) GetCapacity() *Resources {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *NodeRegisterRequest) GetRuntimes() []string {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

func (x *NodeRegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeRegisterRequest) GetHeld() []*Held {
	if x != nil {
		return x.Held
	}
	return nil
}

// Held is one workload on a node: what it declared, and whether it is still
// running and so still using that much of the node.
type Held struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Resources     *Resources             `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	Running       bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Held) Reset() {
	*x = Held{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Held) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Held) ProtoMessage() {}

func (x *Held) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Held.ProtoReflect.Descriptor instead.
func (*Held) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Held) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Held) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Held) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

// Resources are millicores and MiB, matching job.Resources.
type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int64                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int64                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Resources) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Resources) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type NodeRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegisterResponse) Reset() {
	*x = NodeRegisterResponse{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegisterResponse) ProtoMessage() {}

func (x *NodeRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegisterResponse.ProtoReflect.Descriptor instead.
func (*NodeRegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{3}
}

// Workload is a task already translated to what a container needs: the server
// decodes the job, the agent only runs it.
type Workload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Resources     *Resources             `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Runtime       string                 `protobuf:"bytes,8,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Workload) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Workload) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Workload) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Workload) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Workload) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *Workload) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Workload) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Workload) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Workload      *Workload              `protobuf:"bytes,2,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SubmitRequest) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

// Submission and ExecutionStatus carry execution states by their names in
// internal/execution.
type Submission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Submission) Reset() {
	*x = Submission{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Submission) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Submission) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type ExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ExecutionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionStatus) Reset() {
	*x = ExecutionStatus{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStatus) ProtoMessage() {}

func (x *ExecutionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStatus.ProtoReflect.Descriptor instead.
func (*ExecutionStatus) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ExecutionStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ExecutionStatus) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ExecutionStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ExecutionStatus) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

// ExecutionResult's exit_code is unset when the workload never exited, and
// logs are the stored tail.
type ExecutionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      *int32                 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Logs          []byte                 `protobuf:"bytes,3,opt,name=logs,proto3" json:"logs,omitempty"`
	LogsTruncated bool                   `protobuf:"varint,4,opt,name=logs_truncated,json=logsTruncated,proto3" json:"logs_truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ExecutionResult) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *ExecutionResult) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ExecutionResult) GetLogs() []byte {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ExecutionResult) GetLogsTruncated() bool {
	if x != nil {
		return x.LogsTruncated
	}
	return false
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{10}
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_agentrpc_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agentrpc_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_agentrpc_agent_proto_rawDescGZIP(), []int{11}
}

var File_internal_agentrpc_agent_proto protoreflect.FileDescriptor

const file_internal_agentrpc_agent_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/agentrpc/agent.proto\x12\x11vagabond.agent.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x03\n" +
	"\x13NodeRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04pool\x18\x02 \x01(\tR\x04pool\x12J\n" +
	"\x06labels\x18\x03 \x03(\v22.vagabond.agent.v1.NodeRegisterRequest.LabelsEntryR\x06labels\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\x128\n" +
	"\bcapacity\x18\x05 \x01(\v2\x1c.vagabond.agent.v1.ResourcesR\bcapacity\x12\x1a\n" +
	"\bruntimes\x18\x06 \x03(\tR\bruntimes\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12+\n" +
	"\x04held\x18\b \x03(\v2\x17.vagabond.agent.v1.HeldR\x04held\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x04Held\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12:\n" +
	"\tresources\x18\x02 \x01(\v2\x1c.vagabond.agent.v1.ResourcesR\tresources\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\"5\n" +
	"\tResources\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x03R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x03R\x06memory\"\x16\n" +
	"\x14NodeRegisterResponse\"\xea\x02\n" +
	"\bWorkload\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x126\n" +
	"\x03env\x18\x04 \x03(\v2$.vagabond.agent.v1.Workload.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x12:\n" +
	"\tresources\x18\x06 \x01(\v2\x1c.vagabond.agent.v1.ResourcesR\tresources\x123\n" +
	"\atimeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x18\n" +
	"\aruntime\x18\b \x01(\tR\aruntime\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\rSubmitRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x127\n" +
	"\bworkload\x18\x02 \x01(\v2\x1b.vagabond.agent.v1.WorkloadR\bworkload\"C\n" +
	"\n" +
	"Submission\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\"5\n" +
	"\x10ExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xba\x01\n" +
	"\x0fExecutionStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"\xb3\x01\n" +
	"\x0fExecutionResult\x12 \n" +
	"\texit_code\x18\x01 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x12\n" +
	"\x04logs\x18\x03 \x01(\fR\x04logs\x12%\n" +
	"\x0elogs_truncated\x18\x04 \x01(\bR\rlogsTruncatedB\f\n" +
	"\n" +
	"_exit_code\"\x1e\n" +
	"\bLogChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\a\n" +
	"\x05Empty2c\n" +
	"\x04Node\x12[\n" +
	"\bRegister\x12&.vagabond.agent.v1.NodeRegisterRequest\x1a'.vagabond.agent.v1.NodeRegisterResponse2\xe7\x03\n" +
	"\x0fAgentExecutions\x12I\n" +
	"\x06Submit\x12 .vagabond.agent.v1.SubmitRequest\x1a\x1d.vagabond.agent.v1.Submission\x12Q\n" +
	"\x06Status\x12#.vagabond.agent.v1.ExecutionRequest\x1a\".vagabond.agent.v1.ExecutionStatus\x12Q\n" +
	"\x06Result\x12#.vagabond.agent.v1.ExecutionRequest\x1a\".vagabond.agent.v1.ExecutionResult\x12G\n" +
	"\x06Cancel\x12#.vagabond.agent.v1.ExecutionRequest\x1a\x18.vagabond.agent.v1.Empty\x12H\n" +
	"\aRelease\x12#.vagabond.agent.v1.ExecutionRequest\x1a\x18.vagabond.agent.v1.Empty\x12P\n" +
	"\n" +
	"StreamLogs\x12#.vagabond.agent.v1.ExecutionRequest\x1a\x1b.vagabond.agent.v1.LogChunk0\x01B0Z.github.com/afreidah/vagabond/internal/agentrpcb\x06proto3"

var (
	file_internal_agentrpc_agent_proto_rawDescOnce sync.Once
	file_internal_agentrpc_agent_proto_rawDescData []byte
)

func file_internal_agentrpc_agent_proto_rawDescGZIP() []byte {
	file_internal_agentrpc_agent_proto_rawDescOnce.Do(func() {
		file_internal_agentrpc_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agentrpc_agent_proto_rawDesc), len(file_internal_agentrpc_agent_proto_rawDesc)))
	})
	return file_internal_agentrpc_agent_proto_rawDescData
}

var file_internal_agentrpc_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_agentrpc_agent_proto_goTypes = []any{
	(*NodeRegisterRequest)(nil),   // 0: vagabond.agent.v1.NodeRegisterRequest
	(*Held)(nil),                  // 1: vagabond.agent.v1.Held
	(*Resources)(nil),             // 2: vagabond.agent.v1.Resources
	(*NodeRegisterResponse)(nil),  // 3: vagabond.agent.v1.NodeRegisterResponse
	(*Workload)(nil),              // 4: vagabond.agent.v1.Workload
	(*SubmitRequest)(nil),         // 5: vagabond.agent.v1.SubmitRequest
	(*Submission)(nil),            // 6: vagabond.agent.v1.Submission
	(*ExecutionRequest)(nil),      // 7: vagabond.agent.v1.ExecutionRequest
	(*ExecutionStatus)(nil),       // 8: vagabond.agent.v1.ExecutionStatus
	(*ExecutionResult)(nil),       // 9: vagabond.agent.v1.ExecutionResult
	(*LogChunk)(nil),              // 10: vagabond.agent.v1.LogChunk
	(*Empty)(nil),                 // 11: vagabond.agent.v1.Empty
	nil,                           // 12: vagabond.agent.v1.NodeRegisterRequest.LabelsEntry
	nil,                           // 13: vagabond.agent.v1.Workload.EnvEntry
	(*durationpb.Duration)(nil),   // 14: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_internal_agentrpc_agent_proto_depIdxs = []int32{
	12, // 0: vagabond.agent.v1.NodeRegisterRequest.labels:type_name -> vagabond.agent.v1.NodeRegisterRequest.LabelsEntry
	2,  // 1: vagabond.agent.v1.NodeRegisterRequest.capacity:type_name -> vagabond.agent.v1.Resources
	1,  // 2: vagabond.agent.v1.NodeRegisterRequest.held:type_name -> vagabond.agent.v1.Held
	2,  // 3: vagabond.agent.v1.Held.resources:type_name -> vagabond.agent.v1.Resources
	13, // 4: vagabond.agent.v1.Workload.env:type_name -> vagabond.agent.v1.Workload.EnvEntry
	2,  // 5: vagabond.agent.v1.Workload.resources:type_name -> vagabond.agent.v1.Resources
	14, // 6: vagabond.agent.v1.Workload.timeout:type_name -> google.protobuf.Duration
	4,  // 7: vagabond.agent.v1.SubmitRequest.workload:type_name -> vagabond.agent.v1.Workload
	15, // 8: vagabond.agent.v1.ExecutionStatus.started_at:type_name -> google.protobuf.Timestamp
	15, // 9: vagabond.agent.v1.ExecutionStatus.ended_at:type_name -> google.protobuf.Timestamp
	14, // 10: vagabond.agent.v1.ExecutionResult.duration:type_name -> google.protobuf.Duration
	0,  // 11: vagabond.agent.v1.Node.Register:input_type -> vagabond.agent.v1.NodeRegisterRequest
	5,  // 12: vagabond.agent.v1.AgentExecutions.Submit:input_type -> vagabond.agent.v1.SubmitRequest
	7,  // 13: vagabond.agent.v1.AgentExecutions.Status:input_type -> vagabond.agent.v1.ExecutionRequest
	7,  // 14: vagabond.agent.v1.AgentExecutions.Result:input_type -> vagabond.agent.v1.ExecutionRequest
	7,  // 15: vagabond.agent.v1.AgentExecutions.Cancel:input_type -> vagabond.agent.v1.ExecutionRequest
	7,  // 16: vagabond.agent.v1.AgentExecutions.Release:input_type -> vagabond.agent.v1.ExecutionRequest
	7,  // 17: vagabond.agent.v1.AgentExecutions.StreamLogs:input_type -> vagabond.agent.v1.ExecutionRequest
	3,  // 18: vagabond.agent.v1.Node.Register:output_type -> vagabond.agent.v1.NodeRegisterResponse
	6,  // 19: vagabond.agent.v1.AgentExecutions.Submit:output_type -> vagabond.agent.v1.Submission
	8,  // 20: vagabond.agent.v1.AgentExecutions.Status:output_type -> vagabond.agent.v1.ExecutionStatus
	9,  // 21: vagabond.agent.v1.AgentExecutions.Result:output_type -> vagabond.agent.v1.ExecutionResult
	11, // 22: vagabond.agent.v1.AgentExecutions.Cancel:output_type -> vagabond.agent.v1.Empty
	11, // 23: vagabond.agent.v1.AgentExecutions.Release:output_type -> vagabond.agent.v1.Empty
	10, // 24: vagabond.agent.v1.AgentExecutions.StreamLogs:output_type -> vagabond.agent.v1.LogChunk
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_agentrpc_agent_proto_init() }
func file_internal_agentrpc_agent_proto_init() {
	if File_internal_agentrpc_agent_proto != nil {
		return
	}
	file_internal_agentrpc_agent_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agentrpc_agent_proto_rawDesc), len(file_internal_agentrpc_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_agentrpc_agent_proto_goTypes,
		DependencyIndexes: file_internal_agentrpc_agent_proto_depIdxs,
		MessageInfos:      file_internal_agentrpc_agent_proto_msgTypes,
	}.Build()
	File_internal_agentrpc_agent_proto = out.File
	file_internal_agentrpc_agent_proto_goTypes = nil
	file_internal_agentrpc_agent_proto_depIdxs = nil
}
