// -----------------------------------------------------------------------------
// Agent Protocol
//
// Author: Alex Freidah
//
// What a server and its clients say to each other. The client dials the server
// and both sides run gRPC over streams of that one multiplexed connection:
// Node is served by the server and called by the client, ClientExecutions is
// served by the client and called by the server.
// -----------------------------------------------------------------------------

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: internal/agentrpc/agent.proto

package agentrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Node_Register_FullMethodName = "/vagabond.agent.v1.Node/Register"
)

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeClient interface {
	// Register announces the node when the client connects, and again whenever
	// what it reports changes.
	Register(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error)
}

type nodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeClient(cc grpc.ClientConnInterface) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Register(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRegisterResponse)
	err := c.cc.Invoke(ctx, Node_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility.
type NodeServer interface {
	// Register announces the node when the client connects, and again whenever
	// what it reports changes.
	Register(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error)
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServer struct{}

func (UnimplementedNodeServer) Register(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}
func (UnimplementedNodeServer) testEmbeddedByValue()              {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	// If the following call panics, it indicates UnimplementedNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Register(ctx, req.(*NodeRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vagabond.agent.v1.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Node_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/agentrpc/agent.proto",
}

const (
	ClientExecutions_Submit_FullMethodName     = "/vagabond.agent.v1.ClientExecutions/Submit"
	ClientExecutions_Status_FullMethodName     = "/vagabond.agent.v1.ClientExecutions/Status"
	ClientExecutions_Result_FullMethodName     = "/vagabond.agent.v1.ClientExecutions/Result"
	ClientExecutions_Cancel_FullMethodName     = "/vagabond.agent.v1.ClientExecutions/Cancel"
	ClientExecutions_Release_FullMethodName    = "/vagabond.agent.v1.ClientExecutions/Release"
	ClientExecutions_StreamLogs_FullMethodName = "/vagabond.agent.v1.ClientExecutions/StreamLogs"
)

// ClientExecutionsClient is the client API for ClientExecutions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientExecutionsClient interface {
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*Submission, error)
	Status(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionStatus, error)
	Result(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResult, error)
	Cancel(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*Empty, error)
	Release(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*Empty, error)
	StreamLogs(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
}

type clientExecutionsClient struct {
	cc grpc.ClientConnInterface
}

func NewClientExecutionsClient(cc grpc.ClientConnInterface) ClientExecutionsClient {
	return &clientExecutionsClient{cc}
}

func (c *clientExecutionsClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*Submission, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Submission)
	err := c.cc.Invoke(ctx, ClientExecutions_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientExecutionsClient) Status(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionStatus)
	err := c.cc.Invoke(ctx, ClientExecutions_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientExecutionsClient) Result(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResult)
	err := c.cc.Invoke(ctx, ClientExecutions_Result_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientExecutionsClient) Cancel(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientExecutions_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientExecutionsClient) Release(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClientExecutions_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientExecutionsClient) StreamLogs(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientExecutions_ServiceDesc.Streams[0], ClientExecutions_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecutionRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientExecutions_StreamLogsClient = grpc.ServerStreamingClient[LogChunk]

// ClientExecutionsServer is the server API for ClientExecutions service.
// All implementations must embed UnimplementedClientExecutionsServer
// for forward compatibility.
type ClientExecutionsServer interface {
	Submit(context.Context, *SubmitRequest) (*Submission, error)
	Status(context.Context, *ExecutionRequest) (*ExecutionStatus, error)
	Result(context.Context, *ExecutionRequest) (*ExecutionResult, error)
	Cancel(context.Context, *ExecutionRequest) (*Empty, error)
	Release(context.Context, *ExecutionRequest) (*Empty, error)
	StreamLogs(*ExecutionRequest, grpc.ServerStreamingServer[LogChunk]) error
	mustEmbedUnimplementedClientExecutionsServer()
}

// UnimplementedClientExecutionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientExecutionsServer struct{}

func (UnimplementedClientExecutionsServer) Submit(context.Context, *SubmitRequest) (*Submission, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedClientExecutionsServer) Status(context.Context, *ExecutionRequest) (*ExecutionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedClientExecutionsServer) Result(context.Context, *ExecutionRequest) (*ExecutionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedClientExecutionsServer) Cancel(context.Context, *ExecutionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedClientExecutionsServer) Release(context.Context, *ExecutionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedClientExecutionsServer) StreamLogs(*ExecutionRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedClientExecutionsServer) mustEmbedUnimplementedClientExecutionsServer() {}
func (UnimplementedClientExecutionsServer) testEmbeddedByValue()                          {}

// UnsafeClientExecutionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientExecutionsServer will
// result in compilation errors.
type UnsafeClientExecutionsServer interface {
	mustEmbedUnimplementedClientExecutionsServer()
}

func RegisterClientExecutionsServer(s grpc.ServiceRegistrar, srv ClientExecutionsServer) {
	// If the following call panics, it indicates UnimplementedClientExecutionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientExecutions_ServiceDesc, srv)
}

func _ClientExecutions_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientExecutionsServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientExecutions_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientExecutionsServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientExecutions_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientExecutionsServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientExecutions_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientExecutionsServer).Status(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientExecutions_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientExecutionsServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientExecutions_Result_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientExecutionsServer).Result(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientExecutions_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientExecutionsServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientExecutions_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientExecutionsServer).Cancel(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientExecutions_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientExecutionsServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientExecutions_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientExecutionsServer).Release(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientExecutions_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecutionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientExecutionsServer).StreamLogs(m, &grpc.GenericServerStream[ExecutionRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientExecutions_StreamLogsServer = grpc.ServerStreamingServer[LogChunk]

// ClientExecutions_ServiceDesc is the grpc.ServiceDesc for ClientExecutions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientExecutions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vagabond.agent.v1.ClientExecutions",
	HandlerType: (*ClientExecutionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _ClientExecutions_Submit_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _ClientExecutions_Status_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _ClientExecutions_Result_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _ClientExecutions_Cancel_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _ClientExecutions_Release_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _ClientExecutions_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/agentrpc/agent.proto",
}
